name: marriage_app
description: An application that helps to plan marriage ceremonies.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  qr_code_scanner: ^1.0.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  popover: ^0.2.9
  url_launcher: ^6.2.2
  very_good_infinite_list: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/owl.jpg

  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode-VariableFont_wght.ttf
