name: marriage_app
description: An application that helps to plan marriage ceremonies.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  html: ^0.15.4
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  popover: ^0.2.9
  url_launcher: ^6.2.2
  flutter_animate: ^4.3.0
  infinite_scroll_pagination: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/owl.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode-VariableFont_wght.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
